const STRING_KW = {
  TYPEDEF: "KW_TYPEDEF",
  VOID: "KW_VOID",
  CHAR: "KW_CHAR",
  SHORT: "KW_SHORT",
  INT: "KW_INT",
  LONG: "KW_LONG",
  UNSIGNED: "KW_UNSIGNED",
  FLOAT: "KW_FLOAT",
  DOUBLE: "KW_DOUBLE",
  STRUCT: "KW_STRUCT",
  IF: "KW_IF",
  ELSE: "KW_ELSE",
  SWITCH: "KW_SWITCH",
  CASE: "KW_CASE",
  FOR: "KW_FOR",
  WHILE: "KW_WHILE",
  DO: "KW_DO",
  CONTINUE: "KW_CONTINUE",
  BREAK: "KW_BREAK",
  RETURN: "KW_RETURN",
  SIZEOF: "KW_SIZEOF",
};


module.exports = STRING_KW;
