const STRING_KW = {
  TYPEDEF: "KW_TYPEDEF",
  STRUCT: "KW_STRUCT",
  UNION: "KW_UNION",
  ENUM: "KW_ENUM",

  EXTERN: "KW_EXTERN",

  UNSIGNED: "KW_UNSIGNED",
  CHAR: "KW_CHAR",
  SHORT: "KW_SHORT",
  INT: "KW_INT",
  LONG: "KW_LONG",
  FLOAT: "KW_FLOAT",
  DOUBLE: "KW_DOUBLE",

  VOID: "KW_VOID",

  IF: "KW_IF",
  ELSE: "KW_ELSE",
  SWITCH: "KW_SWITCH",
  CASE: "KW_CASE",

  FOR: "KW_FOR",
  WHILE: "KW_WHILE",
  DO: "KW_DO",
  CONTINUE: "KW_CONTINUE",
  BREAK: "KW_BREAK",

  RETURN: "KW_RETURN",
  GOTO: "KW_GOTO",

  SIZEOF: "KW_SIZEOF",
};


module.exports = STRING_KW;

