const STRING_TK = {
  ASTERISK: "TK_ASTERISK",
  AMPERSAND: "TK_AMPERSAND",

  DPLUS: "TK_DPLUS",
  PLUS: "TK_PLUS",

  DMINUS: "TK_DMINUS",
  MINUS: "TK_MINUS",
  POINTSTO: "TK_POINTSTO",

  DIVIDE: "TK_DIVIDE",
  MOD: "TK_MOD",

  ASSIGN: "TK_ASSIGN",
  EQ: "TK_EQ",

  EXCLAMATION: "TK_EXCLAMATION",
  NEQ: "TK_NEQ",

  LT: "TK_LT",
  LEQ: "TK_LEQ",
  GT: "TK_GT",
  GEQ: "TK_GEQ",

  DOT: "TK_DOT",
  ELLIPSIS: "TK_ELLIPSIS",

  TILDE: "TK_TILDE",

  CARET: "TK_CARET",
  AND: "TK_AND",
  OR: "TK_OR",
  DAND: "TK_DAND",
  DOR: "TK_DOR",

  OPENPA: "TK_OPENPA",
  CLOSEPA: "TK_CLOSEPA",
  OPENBR: "TK_OPENBR",
  CLOSEBR: "TK_CLOSEBR",

  BEGIN: "TK_BEGIN",
  END: "TK_END",

  QUESTION: "TK_QUESTION",
  COLON: "TK_COLON",

  SEMICOLON: "TK_SEMICOLON",
  COMMA: "TK_COMMA",
  EOF: "TK_EOF",

  CINT: "TK_CINT",
  CFLOAT: "TK_CFLOAT",
  CCHAR: "TK_CCHAR",
  CSTR: "TK_CSTR",

  IDENT: "TK_IDENT",

  COMMENT1: "TK_COMMENT1",
  COMMENT2: "TK_COMMENT2",
};


module.exports = STRING_TK;

